# Generated by Django 4.2.6 on 2023-12-08 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('Grade', models.IntegerField(primary_key=True, serialize=False)),
                ('Lowsal', models.IntegerField()),
                ('Hisal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_sal', models.IntegerField()),
                ('E_comm', models.IntegerField()),
                ('Emp_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
    ]
